[profile.default]
# Répertoire source des fichiers Solidity
src = "src"

# Répertoire de sortie des artefacts (fichiers compilés)
out = "out"

# Répertoires de bibliothèques externes
libs = ["lib"]

# Remappings utilisés pour les imports
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@chainlink/local/=lib/chainlink-local/",
    "@chainlink/contracts/=lib/chainlink/contracts/src/v0.8/",
]